import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

// ── Full translation dictionary ───────────────────────────────
export const translations = {
    ar: {
        dir: 'rtl',
        // Nav / Sidebar
        dashboard: 'لوحة القيادة',
        myClasses: 'تسجيلاتي',
        myExams: 'اختباراتي',
        myCertificates: 'شهاداتي',
        formations: 'دوراتي',
        settings: 'الإعدادات',
        logout: 'تسجيل الخروج',
        profile: 'الملف الشخصي',
        studentAccount: 'حساب طالب',
        supervisedBy: 'تحت إشراف',
        teacherAccount: 'حساب المعلم',
        // Teacher Dashboard specific
        overviewToday: 'إليك لمحة عن يومك وحلقاتك',
        myStudents: 'طلابي',
        totalEnrolled: 'مسجلون في المجموع',
        attendance: 'الحضور',
        absent: 'غائب',
        generalAverage: 'المعدل العام',
        gradesEntered: 'درجات مُدخلة',
        coursesToday: 'درجات اليوم',
        totalClasses: 'إجمالي الحلقات',
        alerts: 'تنبيهات',
        studentsToFollow: 'طلاب للمتابعة',
        toCorrect: 'للتصحيح',
        evaluations: 'تقييمات',
        difficulties: 'صعوبات',
        studentsBelowQuery: 'طلاب < 10/20',
        completed: 'مكتمل',
        archivedLessons: 'دروس مؤرشفة',
        todaySchedule: 'جدول اليوم',
        markAbsence: 'تسجيل غياب',
        view: 'مشاهدة',
        quickActions: 'إجراءات سريعة',
        enterGrades: 'إدخال الدرجات',
        manageAbsences: 'إدارة الغياب',
        classesAssigned: 'الحلقات المعينة',
        classCount: 'حلقة(ات)',
        noClassAssigned: 'لا يوجد حلقات معينة',
        adminNoClassAssigned: 'لم يعين المسؤول أي حلقة لحسابك بعد.',
        students: 'الطلاب',
        subjects: 'المواد',
        hideStudents: '▲ إخفاء الطلاب',
        showStudents: '▼ عرض الطلاب',
        noStudentsEnrolled: 'لا يوجد طلاب مسجلون.',
        myCoursesMaterials: 'دوراتي وموادي',
        addCourse: '+ إضافة دورة',
        newCourse: 'دورة جديدة',
        editCourse: 'تعديل الدورة',
        titleRequired: 'العنوان *',
        titlePlaceholder: 'مثال: مقدمة في التجويد',
        descriptionText: 'الوصف',
        descriptionPlaceholder: 'صف محتوى الدورة...',
        subjectRequired: 'المادة *',
        selectSubject: '-- اختر مادة --',
        fileUpload: 'ملف (PDF، فيديو، صوت — بحد أقصى 100 ميجابايت)',
        clickToUpload: 'انقر لرفع ملف',
        cancelButton: 'إلغاء',
        createCourseButton: 'إنشاء الدورة',
        updateCourseButton: 'تحديث',
        loadingCourses: 'جاري تحميل الدورات...',
        noCoursesPublished: 'لا يوجد دورات منشورة',
        startCreatingCourse: 'ابدأ بإنشاء مادتك الأولى.',
        createFirstCourse: '+ إنشاء دورة',
        statusDraft: 'مسودة',
        statusPublished: 'منشور',
        statusArchived: 'مؤرشف',
        unknownSubject: 'مادة غير معروفة',
        viewFile: 'عرض الملف',
        demoteToDraft: 'إلى مسودة',
        publishCourse: 'نشر',
        modifyCourse: 'تعديل',
        deleteCourse: 'حذف',
        status: 'الحالة',
        // Classes page
        classesTitle: 'تسجيلاتي',
        classesSubtitle: 'العام الدراسي 1446-1447 هـ',
        teachers: 'المشايخ والأساتذة',
        schedule: 'الجدول الأسبوعي',
        noTeacher: 'لا أساتذة مرتبطون.',
        noSchedule: 'الجدول لم يُعدّ بعد.',
        noClass: 'لم تنضم إلى أي حلقة بعد.',
        enroll: 'الانضمام إلى حلقة',
        enrollTitle: 'الانضمام إلى حلقة جديدة',
        enrollSelect: '-- اختر حلقة --',
        enrollConfirm: 'تأكيد الانضمام',
        enrollNone: 'لا توجد حلقات متاحة.',
        enrollSuccess: 'تم التسجيل بنجاح!',
        cancel: 'إلغاء',
        design1: 'التصميم الأول',
        design2: 'التصميم الثاني',
        
        // New added missing translations for StudentClasses
        filterByChapter: 'تصفية حسب الفصل...',
        filter: 'تصفية...',
        selectAll: 'تحديد الكل',
        noChapterFound: 'لم يتم العثور على أي فصل',
        searchClass: 'البحث عن حلقة...',
        noClassMatchSearch: 'لا توجد حلقة تطابق بحثك.',
        allChapters: 'جميع الفصول',
        chaptersSelected: 'فصول محددة',
        materials: 'مرفقات',
        courseMaterials: 'مرفقات الدورة',
        searchMaterial: 'البحث عن مرفق...',
        allSubjects: 'جميع المواد',
        noMaterialInClass: 'لا توجد مرفقات في الحلقات المحددة.',
        noMaterialMatch: 'لا توجد مرفقات تطابق بحثك.',
        noMaterialForClass: 'لا توجد مرفقات لهذه الحلقة.',
        download: 'تحميل',
        selectClassToView: 'اختر حلقة لعرض التفاصيل',

        // Days
        days: {
            Lundi: 'الإثنين', Mardi: 'الثلاثاء', Mercredi: 'الأربعاء',
            Jeudi: 'الخميس', Vendredi: 'الجمعة', Samedi: 'السبت', Dimanche: 'الأحد'
        },
        // Levels
        niveaux: { debutant: 'مبتدئ', intermediaire: 'متوسط', avance: 'متقدم' },
        // Dashboard
        welcomeBack: 'مرحباً بعودتك',
        mySchedule: 'جدولي الأسبوعي',
        noScheduleYet: 'لا يوجد جدول بعد.',
        viewAll: 'عرض الكل',
        enrolledClasses: 'الحلقات المسجّلة',
        // General
        loading: 'جارٍ التحميل...',
        error: 'حدث خطأ.',
        statusInProgress: 'جاري',
        statusPending: 'قيد الانتظار',
        program: 'المنهج',
        daysAndTimes: 'أيام وأوقات الحلقات',
        loadingSessions: 'جاري تحميل الحلقات...',
        noSessionsScheduled: 'لا توجد حلقات مجدولة حالياً.',
        publishedCourses: 'الدروس المنشورة',
        viewAttendanceHistory: 'سجل الحضور',
        myScheduleBtn: 'الجدول الدراسي',
        room: 'القاعة: ',
        backToHome: 'العودة للرئيسية',
        myDashboard: 'لوحة القيادة',
        myAbsences: 'غياباتي',
        myPayments: 'مدفوعاتي',
        accountPending: 'حساب قيد المراجعة',
        accountPendingDesc: 'حسابك قيد المراجعة من قبل الإدارة.',
        greeting: 'السلام عليكم،',
        greetingSub: 'رحلتك الروحية تستمر اليوم. إليك تقدمك.',
        activatePush: 'تفعيل الإشعارات',
        activatePushDesc: 'احصل على التنبيهات المباشرة الخاصة بالدروس والحضور.',
        activating: 'جاري التفعيل...',
        activateBtn: 'تفعيل',
        ayatOfTheDay: '★ آية اليوم',
        ayatText: 'وَقُل رَّبِّ زِدْنِي عِلْمًا',
        ayatTranslation: '"وقل رب زدني علماً"',
        ayatRef: '— سورة طه، ١١٤',
        globalPerformance: 'أداؤك العام',
        attendanceTracking: 'متابعة الحضور',
        attendanceSub: 'استمر على هذا النحو! المواظبة مفتاح النجاح.',
        presents: 'حضور',
        absences: 'غياب',
        tardies: 'تأخير',
        sessionsLabel: 'الحلقات',
        pendingLabel: 'قيد الانتظار',
        coursesLabel: 'الدروس',
        certificatesLabel: 'الشهادات',
        myEnrolledSessions: 'حلقاتي المسجلة',
        loadingMySessions: 'جاري تحميل الحلقات...',
        noEnrolledSessions: 'لا توجد حلقات مسجلة',
        noEnrolledSessionsDesc: 'لست مسجلاً في أي حلقة حالياً. استكشف برامجنا!',
        viewAvailableSessions: 'تصفح الحلقات المتاحة',
        completedPercentage: 'مكتمل',
        joinBtn: 'انضمام',
        pendingApproval: 'في انتظار الموافقة',
        upcomingExams: 'الاختبارات القادمة',
        noExamsScheduled: 'لا توجد اختبارات مجدولة',
        examsDesc: 'ستظهر تواريخ الاختبارات هنا.',
        browseCalendar: 'تصفح التقويم',
        viewProfileOf: 'عرض ملف:',
        loadingAttendance: 'جاري تحميل سجل حضورك...',
        all: 'الكل',
        excellent: 'ممتاز',
        passable: 'مقبول',
        insufficient: 'ضعيف',
        presenceHeroSubtitle: 'مواظبتك تعكس التزامك الروحي.',
        recordedSessions: 'حلقات مسجلة',
        insufficientAttendance: 'نسبة الحضور ضعيفة',
        contactAdmin: '— يرجى التواصل مع المعلم أو الإدارة لتسوية وضعك.',
        congratsAttendance: 'عمل ممتاز يا ',
        congratsSub: '! مواظبتك المثالية تعزز من تعلمك.',
        history: 'السجل',
        bySession: 'حسب الحلقة',
        noPresenceRecord: 'لا يوجد سجل حضور',
        noSessionFilter: 'لا توجد حلقة تطابق هذا الفلتر.',
        dateAndDay: 'التاريخ واليوم',
        remarks: 'ملاحظات',
        sessionsOfDay: 'حلقات اليوم',
        attendanceSummaryTitle: 'ملخص الحضور',
        type: 'النوع',
        number: 'العدد',
        outOfTotal: 'من إجمالي',
        sessions: 'حلقات',
        noData: 'لا توجد بيانات',
        presenceBySessionEmpty: 'سيظهر سجل حضورك حسب الحلقة هنا.',
        announcementsEvents: 'الإعلانات والأحداث',
        noAnnouncements: 'لا توجد إعلانات حاليا.',
        eventFor: 'حدث يوم:',
        todaysEvent: 'حدث اليوم',
        // Certificates
        certificatesSubtitle: 'شهاداتك في الجلسات المكتملة.',
        certSession: 'الدورة',
        noCertificates: 'لا توجد شهادات بعد',
        noCertificatesDesc: 'ستظهر شهاداتك هنا بعد إتمام الجلسة وسداد الرسوم بالكامل.'
    },
    fr: {
        dir: 'ltr',
        dashboard: 'Tableau de Bord',
        myClasses: 'Mes Inscriptions',
        myExams: 'Mes Examens',
        myCertificates: 'Mes Certificats',
        formations: 'Formations',
        settings: 'Paramètres',
        logout: 'Déconnexion',
        profile: 'Mon Profil',
        studentAccount: 'Compte Étudiant',
        supervisedBy: 'Supervisé par',
        teacherAccount: 'Compte Enseignant',
        overviewToday: 'Voici un aperçu de votre journée et de vos classes',
        myStudents: 'Mes Élèves',
        totalEnrolled: 'inscrits au total',
        attendance: 'Présences',
        absent: 'absents',
        generalAverage: 'Moyenne Générale',
        gradesEntered: 'notes saisies',
        coursesToday: "Cours Aujourd'hui",
        totalClasses: 'classes au total',
        alerts: 'Alertes',
        studentsToFollow: 'Élèves à suivre',
        toCorrect: 'À corriger',
        evaluations: 'Évaluations',
        difficulties: 'Difficultés',
        studentsBelowQuery: 'Élèves < 10/20',
        completed: 'Terminé',
        archivedLessons: 'Leçons Archivées',
        todaySchedule: "Emploi du temps d'aujourd'hui",
        markAbsence: 'Marquer absence',
        view: 'Voir',
        quickActions: 'Actions Rapides',
        enterGrades: 'Saisir des Notes',
        manageAbsences: 'Gérer Absences',
        classesAssigned: 'Mes Classes Assignées',
        classCount: 'classe(s)',
        noClassAssigned: 'Aucune classe assignée',
        adminNoClassAssigned: "L'administrateur n'a pas encore assigné de classe à votre compte.",
        students: 'Élèves',
        subjects: 'Matières',
        hideStudents: '▲ Masquer les élèves',
        showStudents: '▼ Voir les élèves',
        noStudentsEnrolled: 'Aucun élève inscrit.',
        myCoursesMaterials: 'Mes Cours & Supports',
        addCourse: '+ Ajouter un cours',
        newCourse: 'Nouveau Cours',
        editCourse: 'Modifier le cours',
        titleRequired: 'Titre *',
        titlePlaceholder: 'Ex: Introduction au Tajwid',
        descriptionText: 'Description',
        descriptionPlaceholder: 'Décrivez le contenu du cours…',
        subjectRequired: 'Matière *',
        selectSubject: 'Sélectionner une matière',
        fileUpload: 'Fichier (PDF, Vidéo, Audio — max 100MB)',
        clickToUpload: 'Cliquer pour uploader un fichier',
        cancelButton: 'Annuler',
        createCourseButton: 'Créer le cours',
        updateCourseButton: 'Mettre à jour',
        loadingCourses: 'Chargement des cours…',
        noCoursesPublished: 'Aucun cours publié',
        startCreatingCourse: 'Commencez par créer votre premier support de cours.',
        createFirstCourse: '+ Créer un cours',
        statusDraft: 'Brouillon',
        statusPublished: 'Publié',
        statusArchived: 'Archivé',
        unknownSubject: 'Matière inconnue',
        viewFile: 'Voir le fichier',
        demoteToDraft: 'Rétrograder',
        publishCourse: 'Publier',
        modifyCourse: 'Modifier',
        deleteCourse: 'Supprimer',
        status: 'Statut',
        classesTitle: 'Mes Inscriptions',
        classesSubtitle: 'Année scolaire 1446-1447 H',
        teachers: 'Enseignants',
        schedule: 'Emploi du Temps',
        noTeacher: 'Aucun enseignant assigné.',
        noSchedule: 'Planning non configuré.',
        noClass: "Vous n'êtes inscrit(e) dans aucune classe.",
        enroll: "S'inscrire",
        enrollTitle: 'Rejoindre une classe',
        enrollSelect: '-- Choisir une classe --',
        enrollConfirm: "Confirmer l'inscription",
        enrollNone: 'Aucune classe disponible.',
        enrollSuccess: 'Inscription réussie !',
        cancel: 'Annuler',
        design1: 'Design 1',
        design2: 'Design 2',
        filterByChapter: 'Filtrer par chapitre...',
        filter: 'Filtrer...',
        selectAll: 'Sélectionner tout',
        noChapterFound: 'Aucun chapitre trouvé',
        searchClass: 'Rechercher une classe...',
        noClassMatchSearch: 'Aucune classe ne correspond à vos critères.',
        allChapters: 'Tous les chapitres',
        chaptersSelected: 'chapitres sélectionnés',
        materials: 'supports',
        courseMaterials: 'Supports de cours',
        searchMaterial: 'Rechercher un cours...',
        allSubjects: 'Toutes les matières',
        noMaterialInClass: 'Aucun support dans les classes sélectionnées.',
        noMaterialMatch: 'Aucun support ne correspond à votre recherche.',
        noMaterialForClass: 'Aucun support de cours pour cette classe.',
        download: 'Télécharger',
        selectClassToView: 'Sélectionnez une classe pour voir les détails',
        days: {
            Lundi: 'Lundi', Mardi: 'Mardi', Mercredi: 'Mercredi',
            Jeudi: 'Jeudi', Vendredi: 'Vendredi', Samedi: 'Samedi', Dimanche: 'Dimanche'
        },
        niveaux: { debutant: 'Débutant', intermediaire: 'Intermédiaire', avance: 'Avancé' },
        welcomeBack: 'Bon retour',
        mySchedule: 'Mon Emploi du Temps',
        noScheduleYet: 'Aucun cours planifié.',
        viewAll: 'Voir tout',
        enrolledClasses: 'Mes classes',
        loading: 'Chargement...',
        error: 'Une erreur est survenue.',
        statusInProgress: 'EN COURS',
        statusPending: 'EN ATTENTE',
        program: 'Programme',
        daysAndTimes: 'Jours et Horaires des Séances',
        loadingSessions: 'Chargement des séances...',
        noSessionsScheduled: 'Aucune séance planifiée pour le moment.',
        publishedCourses: 'Cours Publiés',
        viewAttendanceHistory: 'Voir mon historique de présence',
        myScheduleBtn: 'Mon emploi du temps',
        room: 'Salle: ',
        backToHome: "Retour à l'accueil",
        myDashboard: 'Mon Tableau de Bord',
        myAbsences: 'Mes Absences',
        myPayments: 'Mes Paiements',
        accountPending: 'Compte en attente',
        accountPendingDesc: 'Le compte est en attente de validation par l\'administration.',
        greeting: 'As-salamou alaykoum,',
        greetingSub: 'Votre voyage spirituel continue aujourd\'hui. Voici votre progression.',
        activatePush: 'Activez vos notifications push',
        activatePushDesc: 'Recevez immédiatement les alertes d\'inscription, paiement et cours directement sur votre navigateur.',
        activating: 'Activation...',
        activateBtn: 'Activer',
        ayatOfTheDay: '★ AYAT DU JOUR',
        ayatText: 'وَقُل رَّبِّ زِدْنِي عِلْمًا',
        ayatTranslation: '"Et dis : Ô mon Seigneur, accrois mes connaissances."',
        ayatRef: '— Sourate Ta-Ha, 114',
        globalPerformance: 'VOTRE PERFORMANCE GLOBALE',
        attendanceTracking: 'Suivi de Présence',
        attendanceSub: 'Continuez ainsi ! Votre régularité est la clé de votre réussite académique et spirituelle.',
        presents: 'Présences',
        absences: 'Absences',
        tardies: 'Retards',
        sessionsLabel: 'SESSIONS',
        pendingLabel: 'ATTENTES',
        coursesLabel: 'COURS',
        certificatesLabel: 'CERTIFICATS',
        myEnrolledSessions: 'Mes Sessions Inscrites',
        loadingMySessions: 'Chargement de vos sessions...',
        noEnrolledSessions: 'Aucune session inscrite',
        noEnrolledSessionsDesc: 'Vous n\'êtes encore inscrit à aucune session. Découvrez nos programmes disponibles !',
        viewAvailableSessions: 'Voir les sessions disponibles',
        completedPercentage: 'COMPLÉTÉ',
        joinBtn: 'Rejoindre',
        pendingApproval: 'En attente d\'approbation',
        upcomingExams: 'Prochains Examens',
        noExamsScheduled: 'Aucun examen prévu',
        examsDesc: 'Les dates de tests seront affichées ici.',
        browseCalendar: 'Parcourir le calendrier',
        viewProfileOf: 'Voir le profil de :',
        loadingAttendance: 'Chargement de votre assiduité...',
        all: 'Tout',
        excellent: 'Excellent',
        passable: 'Passable',
        insufficient: 'Insuffisant',
        presenceHeroSubtitle: 'Votre régularité est le reflet de votre engagement spirituel.',
        recordedSessions: 'séances enregistrées',
        insufficientAttendance: 'Taux d\'assiduité insuffisant',
        contactAdmin: '— Veuillez contacter votre enseignant ou l\'administration pour régulariser votre situation.',
        congratsAttendance: 'Excellent travail, ',
        congratsSub: ' ! Votre assiduité exemplaire favorise grandement votre apprentissage.',
        history: 'Historique',
        bySession: 'Par Session',
        noPresenceRecord: 'Aucune présence enregistrée',
        noSessionFilter: 'Aucune séance ne correspond à ce filtre.',
        dateAndDay: 'Date et Jour',
        remarks: 'Observations',
        sessionsOfDay: 'Séances du jour',
        attendanceSummaryTitle: 'Résumé de Présence',
        type: 'Type',
        number: 'Nombre',
        outOfTotal: 'Sur un total de',
        sessions: 'séances',
        noData: 'Aucune donnée',
        presenceBySessionEmpty: 'Vos présences par session apparaîtront ici.',
        announcementsEvents: 'Annonces & Événements',
        noAnnouncements: 'Aucune annonce pour le moment.',
        eventFor: 'Événement pour le',
        todaysEvent: 'Événement d\'aujourd\'hui',
        // Certificates
        certificatesSubtitle: 'Vos attestations de réussite pour les sessions complétées.',
        certSession: 'Session',
        noCertificates: 'Aucun certificat pour le moment',
        noCertificatesDesc: 'Vos certificats apparaîtront ici après avoir complété et réglé une session avec succès.'
    },
    en: {
        dir: 'ltr',
        dashboard: 'Dashboard',
        myClasses: 'My Inscriptions',
        myExams: 'My Exams',
        myCertificates: 'Certificates',
        formations: 'Formations',
        settings: 'Settings',
        logout: 'Logout',
        profile: 'My Profile',
        studentAccount: 'Student Account',
        supervisedBy: 'Supervised by',
        teacherAccount: 'Teacher Account',
        overviewToday: 'Here is an overview of your day and classes',
        myStudents: 'My Students',
        totalEnrolled: 'total enrolled',
        attendance: 'Attendance',
        absent: 'absent',
        generalAverage: 'General Average',
        gradesEntered: 'grades entered',
        coursesToday: 'Courses Today',
        totalClasses: 'total classes',
        alerts: 'Alerts',
        studentsToFollow: 'Students to monitor',
        toCorrect: 'To correct',
        evaluations: 'Evaluations',
        difficulties: 'Difficulties',
        studentsBelowQuery: 'Students < 10/20',
        completed: 'Completed',
        archivedLessons: 'Archived Lessons',
        todaySchedule: 'Today\'s Schedule',
        markAbsence: 'Mark absence',
        view: 'View',
        quickActions: 'Quick Actions',
        enterGrades: 'Enter Grades',
        manageAbsences: 'Manage Absences',
        classesAssigned: 'Assigned Classes',
        classCount: 'class(es)',
        noClassAssigned: 'No classes assigned',
        adminNoClassAssigned: 'The administrator has not assigned any class to your account yet.',
        students: 'Students',
        subjects: 'Subjects',
        hideStudents: '▲ Hide students',
        showStudents: '▼ Show students',
        noStudentsEnrolled: 'No students enrolled.',
        myCoursesMaterials: 'My Courses & Materials',
        addCourse: '+ Add a course',
        newCourse: 'New Course',
        editCourse: 'Edit Course',
        titleRequired: 'Title *',
        titlePlaceholder: 'Ex: Introduction to Tajweed',
        descriptionText: 'Description',
        descriptionPlaceholder: 'Describe the course content...',
        subjectRequired: 'Subject *',
        selectSubject: '-- Select a subject --',
        fileUpload: 'File (PDF, Video, Audio — max 100MB)',
        clickToUpload: 'Click to upload a file',
        cancelButton: 'Cancel',
        createCourseButton: 'Create Course',
        updateCourseButton: 'Update',
        loadingCourses: 'Loading courses...',
        noCoursesPublished: 'No courses published',
        startCreatingCourse: 'Start by creating your first course material.',
        createFirstCourse: '+ Create a course',
        statusDraft: 'Draft',
        statusPublished: 'Published',
        statusArchived: 'Archived',
        unknownSubject: 'Unknown subject',
        viewFile: 'View file',
        demoteToDraft: 'Demote to Draft',
        publishCourse: 'Publish',
        modifyCourse: 'Modify',
        deleteCourse: 'Delete',
        status: 'Status',
        classesTitle: 'My Inscriptions',
        classesSubtitle: 'Academic Year 1446-1447 H',
        teachers: 'Teachers & Scholars',
        schedule: 'Weekly Schedule',
        noTeacher: 'No teacher assigned.',
        noSchedule: 'Schedule not configured.',
        noClass: 'You are not enrolled in any class.',
        enroll: 'Enroll',
        enrollTitle: 'Join a New Class',
        enrollSelect: '-- Select a class --',
        enrollConfirm: 'Confirm Enrollment',
        enrollNone: 'No classes available.',
        enrollSuccess: 'Successfully enrolled!',
        cancel: 'Cancel',
        design1: 'Design 1',
        design2: 'Design 2',
        filterByChapter: 'Filter by chapter...',
        filter: 'Filter...',
        selectAll: 'Select all',
        noChapterFound: 'No chapter found',
        searchClass: 'Search for a class...',
        noClassMatchSearch: 'No class matches your criteria.',
        allChapters: 'All chapters',
        chaptersSelected: 'chapters selected',
        materials: 'materials',
        courseMaterials: 'Course Materials',
        searchMaterial: 'Search for a material...',
        allSubjects: 'All subjects',
        noMaterialInClass: 'No materials in the selected classes.',
        noMaterialMatch: 'No material matches your search.',
        noMaterialForClass: 'No materials for this class.',
        download: 'Download',
        selectClassToView: 'Select a class to view details',
        days: {
            Lundi: 'Monday', Mardi: 'Tuesday', Mercredi: 'Wednesday',
            Jeudi: 'Thursday', Vendredi: 'Friday', Samedi: 'Saturday', Dimanche: 'Sunday'
        },
        niveaux: { debutant: 'Beginner', intermediaire: 'Intermediate', avance: 'Advanced' },
        welcomeBack: 'Welcome back',
        mySchedule: 'My Weekly Schedule',
        noScheduleYet: 'No classes scheduled.',
        viewAll: 'View all',
        enrolledClasses: 'My Classes',
        loading: 'Loading...',
        error: 'An error occurred.',
        statusInProgress: 'IN PROGRESS',
        statusPending: 'PENDING',
        program: 'Program',
        daysAndTimes: 'Session Days and Times',
        loadingSessions: 'Loading sessions...',
        noSessionsScheduled: 'No sessions scheduled currently.',
        publishedCourses: 'Published Courses',
        viewAttendanceHistory: 'View my attendance history',
        myScheduleBtn: 'My Schedule',
        room: 'Room: ',
        backToHome: 'Back to Home',
        myDashboard: 'My Dashboard',
        myAbsences: 'My Absences',
        myPayments: 'My Payments',
        accountPending: 'Account Pending',
        accountPendingDesc: 'Account is pending administration approval.',
        greeting: 'As-salamu alaykum,',
        greetingSub: 'Your spiritual journey continues today. Here is your progress.',
        activatePush: 'Enable Push Notifications',
        activatePushDesc: 'Receive instant alerts for registration, payments, and classes directly on your browser.',
        activating: 'Enabling...',
        activateBtn: 'Enable',
        ayatOfTheDay: '★ AYAT OF THE DAY',
        ayatText: 'وَقُل رَّبِّ زِدْنِي عِلْمًا',
        ayatTranslation: '"And say: My Lord, increase me in knowledge."',
        ayatRef: '— Surah Ta-Ha, 114',
        globalPerformance: 'YOUR OVERALL PERFORMANCE',
        attendanceTracking: 'Attendance Tracking',
        attendanceSub: 'Keep it up! Consistency is key to your academic and spiritual success.',
        presents: 'Presents',
        absences: 'Absences',
        tardies: 'Tardies',
        sessionsLabel: 'SESSIONS',
        pendingLabel: 'PENDING',
        coursesLabel: 'COURSES',
        certificatesLabel: 'CERTIFICATES',
        myEnrolledSessions: 'My Enrolled Sessions',
        loadingMySessions: 'Loading your sessions...',
        noEnrolledSessions: 'No enrolled sessions',
        noEnrolledSessionsDesc: 'You are not enrolled in any session yet. Discover our available programs!',
        viewAvailableSessions: 'View available sessions',
        completedPercentage: 'COMPLETED',
        joinBtn: 'Join',
        pendingApproval: 'Pending approval',
        upcomingExams: 'Upcoming Exams',
        noExamsScheduled: 'No exams scheduled',
        examsDesc: 'Test dates will be displayed here.',
        browseCalendar: 'Browse the calendar',
        viewProfileOf: 'View profile of:',
        loadingAttendance: 'Loading your attendance...',
        all: 'All',
        excellent: 'Excellent',
        passable: 'Passable',
        insufficient: 'Insufficient',
        presenceHeroSubtitle: 'Your regularity reflects your spiritual commitment.',
        recordedSessions: 'recorded sessions',
        insufficientAttendance: 'Insufficient attendance rate',
        contactAdmin: '— Please contact your teacher or the administration to resolve your situation.',
        congratsAttendance: 'Excellent work, ',
        congratsSub: '! Your exemplary attendance greatly enhances your learning.',
        history: 'History',
        bySession: 'By Session',
        noPresenceRecord: 'No presence recorded',
        noSessionFilter: 'No session matches this filter.',
        dateAndDay: 'Date and Day',
        remarks: 'Remarks',
        sessionsOfDay: 'Sessions of the day',
        attendanceSummaryTitle: 'Attendance Summary',
        type: 'Type',
        number: 'Count',
        outOfTotal: 'Out of a total of',
        sessions: 'sessions',
        noData: 'No data',
        presenceBySessionEmpty: 'Your attendance by session will appear here.',
        announcementsEvents: 'Announcements & Events',
        noAnnouncements: 'No announcements at the moment.',
        eventFor: 'Event for',
        todaysEvent: 'Today\'s Event',
        // Certificates
        certificatesSubtitle: 'Your certificates of completion for finished sessions.',
        certSession: 'Session',
        noCertificates: 'No certificates yet',
        noCertificatesDesc: 'Your certificates will appear here after completing and fully paying for a session.'
    },
};

export const LanguageProvider = ({ children }) => {
    const [lang, setLang] = useState(() => localStorage.getItem('app-lang') || 'ar');

    useEffect(() => {
        localStorage.setItem('app-lang', lang);
        document.documentElement.dir = translations[lang].dir;
        document.documentElement.lang = lang;
    }, [lang]);

    const t = translations[lang];

    return (
        <LanguageContext.Provider value={{ lang, setLang, t }}>
            {children}
        </LanguageContext.Provider>
    );
};
