import nodemailer from 'nodemailer';

/**
 * Utility function to send an email using Nodemailer
 * @param {Object} options - Email options (email, subject, message)
 */
const sendEmail = async (options) => {
    // 1. Create a transporter
    const transporter = nodemailer.createTransport({
        service: 'gmail', // You can change this to another provider if needed
        auth: {
            user: process.env.EMAIL_USER, // Your Gmail address (e.g. test.projet.coranique@gmail.com)
            pass: process.env.EMAIL_PASS  // The 16-character App Password generated by Google
        }
    });

    // 2. Define the email options
    const mailOptions = {
        from: `Association Coranique <${process.env.EMAIL_USER}>`,
        to: options.email,
        subject: options.subject,
        text: options.message,
        // html: options.htmlMessage // Un-comment this if you want to send HTML emails later
    };

    // 3. Actually send the email
    await transporter.sendMail(mailOptions);
};

export default sendEmail;
